{
 "title": "Stardew",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Currency",
   "type": "stat",
   "description": "List of currencies in the game",
   "gridPos": { "h": 18, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sv_money", "legendFormat": "Money" },
    { "expr": "sv_qigems", "legendFormat": "Qi gems" }
   ]
  },
  {
   "title": "Player skill level",
   "type": "gauge",
   "description": "Shows player skills from specific save file",
   "gridPos": { "h": 18, "w": 17, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sv_combatlevel", "legendFormat": "Combat level" },
    { "expr": "sv_fishinglevel", "legendFormat": "Fishing level" },
    { "expr": "sv_foraging", "legendFormat": "Foraging level" },
    { "expr": "sv_farminglevel", "legendFormat": "Farming level" },
    { "expr": "sv_mininglevel", "legendFormat": "Mining level" }
   ]
  },
  {
   "title": "Miscellaneous Stats",
   "type": "stat",
   "description": "A collection of miscellaneous statistics for the player.",
   "gridPos": { "h": 18, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sv_barssmelted", "legendFormat": "{{Name}}" },
    { "expr": "sv_beveragesmade", "legendFormat": "{{Name}}" },
    { "expr": "sv_boulderscracked", "legendFormat": "{{Name}}" },
    { "expr": "sv_cheesemade", "legendFormat": "{{Name}}" },
    { "expr": "sv_fishcaught", "legendFormat": "{{Name}}" },
    { "expr": "sv_giftsgiven", "legendFormat": "{{Name}}" }
   ]
  }
 ]
}